DASH_APP:
  APP_TITLE: Rainfall Data Explorer
  UPDATE_TITLE: Updating...
  DEBUG: False

DASH_THEME:
  THEME: COSMO

TEMPLATE:
  LOGO_SOURCE: https://raw.githubusercontent.com/fiakoenjiniring/static-assets/main/logo/fiakodev-logo-simple-1000-400.png
  WATERMARK_SOURCE: https://raw.githubusercontent.com/fiakoenjiniring/static-assets/main/logo/fiakodev-logo-simple-1000-400.png
  SHOW_LEGEND_INSIDE: False
  SHOW_RANGESELECTOR: False

VERSION: v1.3.0
GITHUB_LINK: https://github.com/fiakoenjiniring/rainfall
GITHUB_REPO: fiakoenjiniring/rainfall
