name: dash-hkrainfall-explorer
channels:
  - defaults
dependencies:
  - python=3.10
  - plotly
  - dash-auth
  - dash
  - numpy
  - pandas
  - console_shortcut
  - matplotlib
  - black
  - pytables
  - pyyaml
  - python-box
  - pip:
    - hidrokit
