name: hidrokit-rainfall
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9.13
  - pandas=1.5.1
  - dash=2.7.0
  - dash-bootstrap-components=1.2.1
  - plotly=5.11.0
  - statsmodels=0.13.5
  - python-box=6.1.0
  - pyyaml=6.0
  - pip
  - pip:
    - dash-bootstrap-templates==1.0.7
    - hidrokit==0.4.1
